version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  open-pull-requests-limit: 100
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
  ignore:
  - dependency-name: git2
    versions:
    - 0.13.17
- package-ecosystem: gitsubmodule
  directory: "/"
  open-pull-requests-limit: 100
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
- package-ecosystem: "github-actions"
  directory: "/"
  open-pull-requests-limit: 100
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
